// Warning: This file is generated by OpenAPI Manager.

use axum::routing::get;
use axum::Router;

use crate::handlers::page;

// -- ROUTER -- //
// Router will be generated here.
pub fn get_router() -> Router {
    Router::new().route("/", get(page::hello_world))
}

// -- MODELS -- //
// Models will be generated here.
